### ISSUE TITLE
page not found

### ISSUE THREAD

**Issue by CaiqueM** [jasrub/indistinguishableFrom-MAS.s65#1]
Hey, I went to http://www.jasrub.com/indistinguishableFrom-MAS.s65/pappers-ghost.html into the text : "  click here to get the file for laser cutting. Cut out the bigger piece from cardboard and the smaller piece from clear acrylic. The red lines are half cuts (for folding). Green and black lines are through cuts."
 I did and the link was crashed. Could you send me the file for laser cutting, by the was the specifications of the project and another files in the same area.

**Comment by jasrub** [comment]
Oops, there was a typo in the file link, should be working now :)
Are there other broken links?

**Comment by CaiqueM** [comment]
nope, thanks so much. Do you have the dimensions of the project, or the
file to edit, or something like?

2018-07-14 13:44 GMT-03:00 Jasmin Rubinovitz <notifications@github.com>:

**Comment by jasrub** [comment]
If you open the .pdf with Adobe Illustrator or similar software you should be able to edit.
Just noticed there is a black square around the shapes, not sure how it got there but you would want to ignore it for cutting (or delete it)

The shorter edge of the plastic piece should be 4.6 inches, so you can scale everything accordingly
(the file should be to scale I think)

**Comment by CaiqueM** [comment]
Hey, it's me again :)
I've searched for this topic. What was the software you used to modify the
cardboard? I would like to add some parts on my cardboard, but I do not
know if is going to be possible to do it in an easy way. Is this software
simple to handle? I've never tested AutoCAD or SolidWorks or things like
this.

2018-07-15 11:41 GMT-03:00 Jasmin Rubinovitz <notifications@github.com>:

**Comment by jasrub** [comment]
Because it's a 2d file I used Adobe Illustrator. Any vectors graphic software will probably work (maybe incscape or something similar. photoshop may work too)

**Comment by CaiqueM** [comment]
thank you!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

2018-07-29 23:21 GMT-03:00 Jasmin Rubinovitz <notifications@github.com>:

**Comment by CaiqueM** [comment]
Hey, I got the software, but I do not get when you said : "   The shorter
edge of the plastic piece should be 4.6 inches, so you can scale everything
accordingly  " I do not see any plastic at all, just the paper binders,
but, I not sure if they could be 4.6 inches. As you can see on the image,
there is no plastic part at all. PS: I have already printed the picture,
but it was too short, so I could not compare it :(
[image: image.png]

Em seg, 30 de jul de 2018 às 05:45, Caique Moura <caiquemourasilva@gmail.com>
escreveu:

**Comment by CaiqueM** [comment]
I did a mistake, I got what you said, sorry :)

Em seg, 6 de ago de 2018 às 20:21, Caique Moura <caiquemourasilva@gmail.com>
escreveu:
